name = "Fabric of Joy"
author = "Keksiu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1755f3dd1fca78a40dcccdf27994dd1097ca60572bf9b8e9c2550f5c0e3f0f7e"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21.1"]
