name = "Fabric of Joy"
author = "Keksiu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "91fa1143eaa615ab54df9c886a566909f120abf629694dd5f8c9ed8eaadaf31d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
