name = "Fabric of Joy"
author = "Keksiu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ee0eed62b52ad93a5ddfef7089d52fdac388a5d5ceb273fa96cf033ab51f8f4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
